SELECT TOP (1000) [Fecha]
      ,[Ticker]
      ,[Precio]
      ,[CambioPorcentaje]
      ,[Volumen]
      ,[Vacío]
      ,[Categoria]
      ,[Noticia]
      ,[ShsFloat]
      ,[ShortFloat]
      ,[ShortRatio]
      ,[AvgVolume]
      ,[CashSh]
  FROM [FinvizData].[dbo].[TablaFinviz]